name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: "kumaryoya"
          ICON_FIRST: "#030E21"
          ICON_SECOND: "#1688BF"
          BACKGROUND_FIRST: "#020E27"
          BACKGROUND_SECOND: "#0E5593"
          LANG: "ja"
          CARD_WIDTH: "400"
          UPDATE_TIME: "false"
