name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: "kumaryoya"
          ICON_FIRST: "#05aeff"
          ICON_SECOND: "#05aeff"
          BACKGROUND_FIRST: "#050f2c"
          BACKGROUND_SECOND: "#050f2c"
          LANG: "ja"
          CARD_WIDTH: "300"
          README_FILE: "README.md"
          
